[package]
name = "cargo-pio"
version = "0.20.0"
authors = ["Ivan Markov <ivan.markov@gmail.com>"]
edition = "2018"

[lib]
name = "pio"
path = "src/pio.rs"

[[bin]]
name = "cargo-pio"
path = "src/main.rs"

[[bin]]
name = "cargo-pio-link"
path = "src/link.rs"

[dependencies]
which = "4.1"
tempfile = "3.2"
globwalk = "0.8"
anyhow = {version = "1", features = ["backtrace"]}
log = "0.4"
env_logger = "0.8"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
ureq = "2.1"
clap = "2.3"
toml = "0.5"
cargo_toml = "0.9"
bindgen = "0.57"
